- name: Copy certificate files
  copy: src=certs/{{ item }}
        dest=/var/lib/kubernetes/{{ item }}
        owner=root
        group=root
        mode=0400
  with_items:
      - ca.pem
      - kubernetes.pem
      - kubernetes-key.pem
- name: Make sure the kubernetes folders are created
  file: path={{ item }}
        owner=root
        group=root
        state=directory
  with_items:
      - /var/lib/kubernetes
- name: Copy kubernetes executables
  copy: src={{ item }}
        dest=/usr/bin/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
      - kube-apiserver
      - kube-controller-manager
      - kubectl
      - kube-scheduler
- name: Copy kubernetes auth files
  file: src={{ item }}
        dest=/var/lib/kubernetes/{{ item }}
  with_items:
      - token.csv
      - authorization-policy.jsonl
