- name: Make sure the kubernetes folders are created
  file: path={{ item }}
        owner=root
        group=root
        state=directory
  with_items:
      - /var/lib/kubernetes
- name: Copy certificate files
  copy: src=certs/{{ item }}
        dest=/var/lib/kubernetes/{{ item }}
        owner=root
        group=root
        mode=0400
  with_items:
      - ca.pem
      - kubernetes.pem
      - kubernetes-key.pem
- name: Copy kubernetes executables
  copy: src={{ item }}
        dest=/usr/bin/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
      - kube-apiserver
      - kube-controller-manager
      - kubectl
      - kube-scheduler
- name: Copy kubernetes auth files
  copy: src={{ item }}
        dest=/var/lib/kubernetes/{{ item }}
        owner=root
        group=root
  with_items:
      - token.csv
      - authorization-policy.jsonl
- name: Kubernetes API Service
  template: dest=/etc/systemd/system/kube-apiserver.service
            src=kube-apiserver.service.j2
  notify: restart kube apiserver
- name: Kubernetes Controller Manager
  template: dest=/etc/systemd/system/kube-controller-manager.service
            src=kube-controller-manager.service.j2
  notify: restart kube controller manager
- name: Kubernetes Scheduler
  template: dest=/etc/systemd/system/kube-scheduler.service
            src=kube-scheduler.service.j2
  notify: restart kube scheduler
