---
- name: Copy etcd binaries
  copy: src={{ item }}
        dest=/usr/bin/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
      - etcd
      - etcdctl
- name: Make sure etcd folders are created
  file: path={{ item }}
        owner=root
        group=root
        state=directory
  with_items:
      - /etc/etcd
      - /var/lib/etcd
- name: Configure etcd
  template: dest=/etc/systemd/system/etcd.service
            src=etcd.service.j2
  notify: restart etcd
