---
- name: Make sure kubelet folder exists
  file: path=/var/lib/kubelet
        owner=root
        group=root
        state=directory
- name: Copy kubelet binaries
  copy: src={{ item }}
        dest=/usr/bin/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
      - kubectl
      - kubelet
- name: Configure kubelet
  template: src=kubeconfig.j2
            dest=/var/lib/kubelet/kubeconfig
- name: Configure kubelet systemd unit
  template: src=kubelet.service.j2
            dest=/etc/systemd/system/kubelet.service
  notify: restart kubelet
