---
- hosts: etcd
  become: yes
  gather_facts: no
  pre_tasks:
      - name: install python2
        raw: sudo apt-get -y install python
  roles:
      - certs
      - etcd
- hosts: controller
  become: yes
  gather_facts: no
  pre_tasks:
      - name: install python2
        raw: sudo apt-get -y install python
  roles:
      - certs
      - controller
- hosts: worker
  become: yes
  gather_facts: no
  pre_tasks:
      - name: install python2
        raw: sudo apt-get -y install python
  roles:
      - certs
      - docker
