---
- name: restart kube apiserver
  systemd: enabled=yes
           state=restarted
           name=kube-apiserver.service
           daemon_reload=yes

- name: restart kube controller manager
  systemd: enabled=yes
           state=restarted
           name=kube-controller-manager.service
           daemon_reload=yes

- name: restart kube scheduler
  systemd: enabled=yes
           state=restarted
           name=kube-scheduler.service
           daemon_reload=yes
